#!/bin/bash

##########
#update the variables below as needed
##########

JOB=diSO2_1CHplus_B3LYP_TZP_KlamtWater_solvfrag_towardC.CH2	#this is the name of your job
		#make sure there are no spaces in the name
CURDIR=`'pwd'`  #do not change this line
TIME='24:00:00' #run time (hh:mm:ss) - 2 hours
NODES=1		#total number of nodes
TASKS=128        #total number of mpi tasks requested
		#should be 128 tasks per node

#########
#Do not change this next section!
#########
cat > $JOB.sbatch << EOF_ALL
#!/bin/sh

#SBATCH -J $JOB  	         # job name
#SBATCH -o $CURDIR/$JOB.out
#SBATCH -e $CURDIR/$JOB.err
#SBATCH -N $NODES                # total number of nodes 
#SBATCH -n $TASKS                # total number of mpi tasks requested
#SBATCH -t $TIME                 # run time (hh:mm:ss) - 1.5 hours
#SBATCH --exclude=c004
#!/bin/sh

AMS_JOBNAME=$JOB $AMSBIN/ams << eor

########
#replace the lines below with your adf input file
#starting with the "Task"
########

Task SinglePoint
System
    Atoms
        C 0.1268116543720141 -0.01182441458212553 2.104365806731752 region=CH2 adf.R=2.00
        H 0.08616916692092405 -0.9055033259943466 2.722099299438723 region=CH2 adf.R=1.30
        H 0.08048361732264923 0.8748423546815108 2.731715910978156 region=CH2 adf.R=1.30
    End
    Symmetrize Yes
    BondOrders
         1 2 1.0
         1 3 1.0
    End
End
Symmetry
    SymmetrizeTolerance 1.0e-7
End

Engine ADF
    Basis
        Type TZP
        Core None
    End
    XC
        Hybrid B3LYP
    End
    Title CH2 fragment
    Relativity
        Level None
    End
    Symmetry NOSYM
    Solvation
        Surf Delley
        Solv name=Water cav0=0.0 cav1=0.0067639
        Charged method=CONJ
        C-Mat POT
        SCF VAR ALL 
        CSMRSP
    End
EndEngine
eor

########
#do not change the rest of the file!
########

mv $JOB.results/ams.log $JOB.logfile
rm slurm-*.out

EOF_ALL

sbatch < $JOB.sbatch
