#!/bin/bash

##########
#update the variables below as needed
##########

JOB=HEXS_I2_B3LYP_TZP_gas_fragments_noH2O.CH2OH	#this is the name of your job
		#make sure there are no spaces in the name
CURDIR=`'pwd'`  #do not change this line
TIME='24:00:00' #run time (hh:mm:ss) - 2 hours
NODES=1		#total number of nodes
TASKS=128        #total number of mpi tasks requested
		#should be 128 tasks per node

#########
#Do not change this next section!
#########
cat > $JOB.sbatch << EOF_ALL
#!/bin/sh

#SBATCH -J $JOB  	         # job name
#SBATCH -o $CURDIR/$JOB.out
#SBATCH -e $CURDIR/$JOB.err
#SBATCH -N $NODES                # total number of nodes 
#SBATCH -n $TASKS                # total number of mpi tasks requested
#SBATCH -t $TIME                 # run time (hh:mm:ss) - 1.5 hours
#SBATCH --exclude=c004
#!/bin/sh

AMS_JOBNAME=$JOB $AMSBIN/ams << eor

########
#replace the lines below with your adf input file
#starting with the "Task"
########

Task SinglePoint
System
    Atoms
        H -0.06229650277101506 -2.001502193410294 4.340193340676283 region=CH2OH
        H -0.2553618396922027 -3.170983473731289 1.804897065552974 region=CH2OH
        H -1.049606972438119 -1.669328996298632 2.36670809701504 region=CH2OH
        C -0.1543476356942321 -2.278984614534211 2.421997142328885 region=CH2OH
        O 0.2058590260912515 -2.671108540067862 3.692680782989158 region=CH2OH
    End
    Symmetrize Yes
    Charge 1.0
    BondOrders
         4 2 1.0
         4 3 1.0
         5 1 1.0
         5 4 1.0
    End
End
Symmetry
    SymmetrizeTolerance 1.0e-7
End

Engine ADF
    Basis
        Type TZP
        Core None
    End
    XC
        Hybrid B3LYP
    End
    Title CH2OH fragment
    Relativity
        Level None
    End
    Symmetry NOSYM
EndEngine
eor

########
#do not change the rest of the file!
########


mv $JOB.results/ams.log $JOB.logfile
rm slurm-*.out

EOF_ALL

sbatch < $JOB.sbatch
