#!/bin/bash

##########
#update the variables below as needed
##########

JOB=HEXS_I2_B3LYP_TZP_KlamtWater_solvfragments_noH2O.CH2OH	#this is the name of your job
		#make sure there are no spaces in the name
CURDIR=`'pwd'`  #do not change this line
TIME='24:00:00' #run time (hh:mm:ss) - 2 hours
NODES=1		#total number of nodes
TASKS=128        #total number of mpi tasks requested
		#should be 128 tasks per node

#########
#Do not change this next section!
#########
cat > $JOB.sbatch << EOF_ALL
#!/bin/sh

#SBATCH -J $JOB  	         # job name
#SBATCH -o $CURDIR/$JOB.out
#SBATCH -e $CURDIR/$JOB.err
#SBATCH -N $NODES                # total number of nodes 
#SBATCH -n $TASKS                # total number of mpi tasks requested
#SBATCH -t $TIME                 # run time (hh:mm:ss) - 1.5 hours
#SBATCH --exclude=c004
#!/bin/sh

AMS_JOBNAME=$JOB $AMSBIN/ams << eor

########
#replace the lines below with your adf input file
#starting with the "Task"
########

Task SinglePoint
System
    Atoms
        H -0.1432779891193163 -1.91215423585563 4.341398170455021 region=CH2OH adf.R=1.350
        H -0.224353514664215 -3.154910204046378 1.829942738024501 region=CH2OH adf.R=1.350
        H -1.03935839821744 -1.642379006134552 2.331502770822842 region=CH2OH adf.R=1.350
        C -0.1542597083133041 -2.257586582418535 2.438129850422862 region=CH2OH adf.R=1.700
        O 0.1255702061048508 -2.625077756510818 3.740955435788575 region=CH2OH adf.R=1.517
    End
    Symmetrize Yes
    Charge 1.0
    BondOrders
         4 2 1.0
         4 3 1.0
         5 1 1.0
         5 4 1.0
    End
End
Symmetry
    SymmetrizeTolerance 1.0e-7
End

Engine ADF
    Basis
        Type TZP
        Core None
    End
    XC
        Hybrid B3LYP
    End
    Title CH2OH fragment
    Relativity
        Level None
    End
    Symmetry NOSYM
    Solvation
        Surf Delley
        Solv name=Water cav0=0.0 cav1=0.0067639
        Charged method=CONJ
        C-Mat POT
        SCF VAR ALL 
        CSMRSP
    End
EndEngine
eor

########
#do not change the rest of the file!
########


mv $JOB.results/ams.log $JOB.logfile
rm slurm-*.out

EOF_ALL

sbatch < $JOB.sbatch
