#!/bin/bash

##########
#update the variables below as needed
##########

JOB=monoSO2_1CHplus_B3LYP_TZP_KlamtWater_GO_sym_QTAIM	#this is the name of your job
		#make sure there are no spaces in the name
CURDIR=`'pwd'`  #do not change this line
TIME='24:00:00' #run time (hh:mm:ss) - 2 hours
NODES=1		#total number of nodes
TASKS=128        #total number of mpi tasks requested
		#should be 128 tasks per node

#########
#Do not change this next section!
#########
cat > $JOB.sbatch << EOF_ALL
#!/bin/sh

#SBATCH -J $JOB  	         # job name
#SBATCH -o $CURDIR/$JOB.out
#SBATCH -e $CURDIR/$JOB.err
#SBATCH -N $NODES                # total number of nodes 
#SBATCH -n $TASKS                # total number of mpi tasks requested
#SBATCH -t $TIME                 # run time (hh:mm:ss) - 1.5 hours
#SBATCH --exclude=c004
#!/bin/sh

AMS_JOBNAME=$JOB $AMSBIN/ams << eor

########
#replace the lines below with your adf input file
#starting with the "Task"
########

Task GeometryOptimization
UseSymmetry No
Properties
    PESPointCharacter Yes
End
System
    Atoms
        H 0.64927433 -1.10434629 2.08750352 adf.R=1.30
        H -0.59127576 -2.03576785 1.22679226 adf.R=1.30
        C 1.64960157 0.13189598 0.0 adf.R=2.00
        N 0.84685632 -1.10714746 0.0 adf.R=1.83
        N 0.78467156 1.32835938 0.0 adf.R=1.83
        N -0.90041044 0.06678761 -1.29774482 adf.R=1.83
        S -1.96845791 0.03951761 0.0 adf.R=2.16
        N -0.90041044 0.06678761 1.29774482 adf.R=1.83
        O -2.72635829 1.26952167 0.0 adf.R=1.72
        O -2.66260134 -1.22756086 0.0 adf.R=1.72
        C 0.01543823 -1.1353816 -1.20352788 adf.R=2.00
        C -0.04710406 1.31412791 1.20352787 adf.R=2.00
        C -0.04710406 1.31412791 -1.20352787 adf.R=2.00
        C 0.01543823 -1.1353816 1.20352788 adf.R=2.00
        H 0.64927433 -1.10434629 -2.08750352 adf.R=1.30
        H -0.59127576 -2.03576785 -1.22679226 adf.R=1.30
        H 0.58748996 1.31547888 2.08750352 adf.R=1.30
        H -0.69897591 2.18237923 1.22679226 adf.R=1.30
        H -0.69897591 2.18237923 -1.22679226 adf.R=1.30
        H 0.58748996 1.31547888 -2.08750352 adf.R=1.30
        H 2.28044254 0.14800298 -0.88768611 adf.R=1.30
        H 2.28044254 0.14800298 0.88768611 adf.R=1.30
        H 1.48653031 -1.93714805 0.0 adf.R=1.30
    End
    Charge 1.0
    BondOrders
         1 14 1.0
         2 14 1.0
         3 4 1.0
         3 5 1.0
         3 21 1.0
         3 22 1.0
         4 11 1.0
         4 14 1.0
         4 23 1.0
         5 12 1.0
         5 13 1.0
         6 7 1.0
         6 11 1.0
         6 13 1.0
         7 8 1.0
         7 9 2.0
         7 10 2.0
         8 12 1.0
         8 14 1.0
         11 15 1.0
         11 16 1.0
         12 17 1.0
         12 18 1.0
         13 19 1.0
         13 20 1.0
    End
End

Engine ADF
    Basis
        Type TZP
        Core None
    End
    Save TAPE10
    XC
        Hybrid B3LYP
    End
    Relativity
        Level None
    End
    Symmetry C(S)
    Solvation
        Surf Delley
        Solv name=Water cav0=0.0 cav1=0.0067639
        Charged method=CONJ
        C-Mat POT
        SCF VAR ALL 
        CSMRSP
    End
    QTAIM
        Enabled Yes
        AnalysisLevel Full
    End
EndEngine
eor

########
#do not change the rest of the file!
########


mv $JOB.results/ams.log $JOB.logfile
rm slurm-*.out

EOF_ALL

sbatch < $JOB.sbatch
