#!/bin/bash

##########
#update the variables below as needed
##########

JOB=monoSO2_1CHplus_B3LYP_TZP_KlamtWater_solvfrag_towardC.CH2	#this is the name of your job
		#make sure there are no spaces in the name
CURDIR=`'pwd'`  #do not change this line
TIME='24:00:00' #run time (hh:mm:ss) - 2 hours
NODES=1		#total number of nodes
TASKS=128        #total number of mpi tasks requested
		#should be 128 tasks per node

#########
#Do not change this next section!
#########
cat > $JOB.sbatch << EOF_ALL
#!/bin/sh

#SBATCH -J $JOB  	         # job name
#SBATCH -o $CURDIR/$JOB.out
#SBATCH -e $CURDIR/$JOB.err
#SBATCH -N $NODES                # total number of nodes 
#SBATCH -n $TASKS                # total number of mpi tasks requested
#SBATCH -t $TIME                 # run time (hh:mm:ss) - 1.5 hours
#SBATCH --exclude=c004
#!/bin/sh

AMS_JOBNAME=$JOB $AMSBIN/ams << eor

########
#replace the lines below with your adf input file
#starting with the "Task"
########

Task SinglePoint
UseSymmetry No
System
    Atoms
        H 2.299399902307833 0.1595637021499613 0.8925487106462859 region=CH2 adf.R=1.30
        H 2.299399901945604 0.1595637021722017 -0.8925487102510954 region=CH2 adf.R=1.30
        C 1.680498000503118 0.1834752667065609 3.116206395640207e-10 region=CH2 adf.R=2.00
    End
    Symmetrize Yes
    BondOrders
         3 1 1.0
         3 2 1.0
    End
End
Symmetry
    SymmetrizeTolerance 1.0e-7
End

Engine ADF
    Basis
        Type TZP
        Core None
    End
    XC
        Hybrid B3LYP
    End
    Title CH2 fragment
    Relativity
        Level None
    End
    Symmetry NOSYM
    Solvation
        Surf Delley
        Solv name=Water cav0=0.0 cav1=0.0067639
        Charged method=CONJ
        C-Mat POT
        SCF VAR ALL 
        CSMRSP
    End
EndEngine
eor

########
#do not change the rest of the file!
########

mv $JOB.results/ams.log $JOB.logfile
rm slurm-*.out

EOF_ALL

sbatch < $JOB.sbatch
