#!/bin/bash

##########
#update the variables below as needed
##########

JOB=TETSHplus_B3LYP_TZP_KlamtWater_GO_sym_QTAIM	#this is the name of your job
		#make sure there are no spaces in the name
CURDIR=`'pwd'`  #do not change this line
TIME='24:00:00' #run time (hh:mm:ss) - 2 hours
NODES=1		#total number of nodes
TASKS=128        #total number of mpi tasks requested
		#should be 128 tasks per node

#########
#Do not change this next section!
#########
cat > $JOB.sbatch << EOF_ALL
#!/bin/sh

#SBATCH -J $JOB  	         # job name
#SBATCH -o $CURDIR/$JOB.out
#SBATCH -e $CURDIR/$JOB.err
#SBATCH -N $NODES                # total number of nodes 
#SBATCH -n $TASKS                # total number of mpi tasks requested
#SBATCH -t $TIME                 # run time (hh:mm:ss) - 1.5 hours
#SBATCH --exclude=c004
#!/bin/sh

AMS_JOBNAME=$JOB $AMSBIN/ams << eor

########
#replace the lines below with your adf input file
#starting with the "Task"
########

Task GeometryOptimization
UseSymmetry No
Properties
    PESPointCharacter Yes
End
System
    Atoms
        O 2.70945564 -1.33221057 0.0 adf.R=1.72
        O 2.69512011 1.17319992 0.0 adf.R=1.72
        S 1.99468774 -0.08355413 0.0 adf.R=2.16
        N 0.90400254 -0.08979478 -1.29036149 adf.R=1.83
        N 0.90400254 -0.08979478 1.29036149 adf.R=1.83
        N -0.78957932 1.19120414 0.0 adf.R=1.83
        S -1.8728125 -0.10568329 0.0 adf.R=2.16
        N -0.77480961 -1.39008999 0.0 adf.R=1.83
        O -2.58053886 -0.10973283 1.25270996 adf.R=1.72
        O -2.58053886 -0.10973283 -1.25270996 adf.R=1.72
        C 0.05383863 1.13691414 -1.23147909 adf.R=2.00
        C 0.0679319 -1.32615206 1.23147912 adf.R=2.00
        C 0.05383863 1.13691414 1.23147909 adf.R=2.00
        C 0.0679319 -1.32615206 -1.23147912 adf.R=2.00
        H 0.68962875 2.01571872 -1.24091751 adf.R=1.30
        H -0.58682826 1.14239126 -2.10680298 adf.R=1.30
        H 0.71373687 -2.1976235 1.24091763 adf.R=1.30
        H -0.57263041 -1.33896021 2.10680296 adf.R=1.30
        H -0.58682826 1.14239126 2.10680298 adf.R=1.30
        H 0.68962875 2.01571872 1.24091751 adf.R=1.30
        H -0.57263041 -1.33896021 -2.10680296 adf.R=1.30
        H 0.71373687 -2.1976235 -1.24091763 adf.R=1.30
        H -1.34034438 2.08161241 0.0 adf.R=1.30
    End
    Charge 1.0
    BondOrders
         1 3 2.0
         2 3 2.0
         3 4 1.0
         3 5 1.0
         4 11 1.0
         4 14 1.0
         5 12 1.0
         5 13 1.0
         6 7 1.0
         6 11 1.0
         6 13 1.0
         6 23 1.0
         7 8 1.0
         7 9 2.0
         7 10 2.0
         8 12 1.0
         8 14 1.0
         11 15 1.0
         11 16 1.0
         12 17 1.0
         12 18 1.0
         13 19 1.0
         13 20 1.0
         14 21 1.0
         14 22 1.0
    End
End

Engine ADF
    Basis
        Type TZP
        Core None
    End
    Save TAPE10
    XC
        Hybrid B3LYP
    End
    Relativity
        Level None
    End
    Symmetry C(S)
    Solvation
        Surf Delley
        Solv name=Water cav0=0.0 cav1=0.0067639
        Charged method=CONJ
        C-Mat POT
        SCF VAR ALL 
        CSMRSP
    End
    QTAIM
        Enabled Yes
        AnalysisLevel Full
    End
EndEngine
eor

########
#do not change the rest of the file!
########


mv $JOB.results/ams.log $JOB.logfile
rm slurm-*.out

EOF_ALL

sbatch < $JOB.sbatch
