#!/bin/bash

##########
#update the variables below as needed
##########

JOB=TETS_I1_KlamtWater_B3LYP_TZP_QTAIM	#this is the name of your job
		#make sure there are no spaces in the name
CURDIR=`'pwd'`  #do not change this line
TIME='24:00:00' #run time (hh:mm:ss) - 2 hours
NODES=1		#total number of nodes
TASKS=128        #total number of mpi tasks requested
		#should be 128 tasks per node

#########
#Do not change this next section!
#########
cat > $JOB.sbatch << EOF_ALL
#!/bin/sh

#SBATCH -J $JOB  	         # job name
#SBATCH -o $CURDIR/$JOB.out
#SBATCH -e $CURDIR/$JOB.err
#SBATCH -N $NODES                # total number of nodes 
#SBATCH -n $TASKS                # total number of mpi tasks requested
#SBATCH -t $TIME                 # run time (hh:mm:ss) - 1.5 hours
#SBATCH --exclude=c004
#!/bin/sh

AMS_JOBNAME=$JOB $AMSBIN/ams << eor

########
#replace the lines below with your adf input file
#starting with the "Task"
########

Task SinglePoint
System
    Atoms
        O 2.5562 -0.6007 -0.0922 adf.R=1.72
        O 1.4941 0.5914 1.8287 adf.R=1.72
        S 1.3782 -0.0464 0.5393 adf.R=2.16
        N 0.724 1.0499 -0.5498 adf.R=1.83
        N 0.1277 -1.1419 0.631 adf.R=1.83
        N -1.6402 1.2646 0.2044 adf.R=1.83
        S -2.1678 0.2945 -1.0715 adf.R=2.16
        N -0.7989000000000001 -0.5533 -1.5495 adf.R=1.83
        O -3.1367 -0.6237 -0.5316 adf.R=1.72
        O -2.4848 1.1765 -2.1644 adf.R=1.72
        C -0.3372 1.9407 -0.0498 adf.R=2.00
        C -0.3774 -1.653 -0.676 adf.R=2.00
        C -2.0045 0.9016999999999999 1.5426 adf.R=2.00
        C 0.3272 0.3797 -1.8074 adf.R=2.00
        H -0.0186 2.4132 0.8719 adf.R=1.30
        H -0.4783 2.7003 -0.8137 adf.R=1.30
        H 0.3811 -2.2112 -1.2241 adf.R=1.30
        H -1.2178 -2.3025 -0.4589 adf.R=1.30
        H -1.2668 1.2806 2.2393 adf.R=1.30
        H -2.1603 -0.1594 1.687 adf.R=1.30
        H 0.0325 1.1356 -2.527 adf.R=1.30
        H 1.1581 -0.1936 -2.2046 adf.R=1.30
        H 0.3542 -1.895 1.2781 adf.R=1.30
        O -3.2761 1.531 1.9599 adf.R=1.72
        H -4.0366 1.0679 1.5654 adf.R=1.30
        O -3.5775 3.921 1.7148 adf.R=1.72
        H -3.372 2.6532 1.8046 adf.R=1.30
        H -3.0368 4.4517 2.3226 adf.R=1.30
        H -3.4451 4.2898 0.8265 adf.R=1.30
    End
    Charge 1.0
    BondOrders
         1 3 2.0
         2 3 2.0
         3 4 1.0
         3 5 1.0
         4 11 1.0
         4 14 1.0
         5 12 1.0
         5 23 1.0
         6 7 1.0
         6 11 1.0
         6 13 1.0
         7 8 1.0
         7 9 2.0
         7 10 2.0
         8 12 1.0
         8 14 1.0
         11 15 1.0
         11 16 1.0
         12 17 1.0
         12 18 1.0
         13 19 1.0
         13 20 1.0
         13 24 1.0
         14 21 1.0
         14 22 1.0
         24 25 1.0
         26 28 1.0
         26 29 1.0
         27 24 1.0
    End
End

Engine ADF
    Basis
        Type TZP
        Core None
    End
    Save TAPE10
    XC
        Hybrid B3LYP
    End
    Relativity
        Level None
    End
    Solvation
        Surf Delley
        Solv name=Water cav0=0.0 cav1=0.0067639
        Charged method=CONJ
        C-Mat POT
        SCF VAR ALL 
        CSMRSP
    End
    QTAIM
        Enabled Yes
        AnalysisLevel Extended
    End
EndEngine
eor

########
#do not change the rest of the file!
########


mv $JOB.results/ams.log $JOB.logfile
rm slurm-*.out

EOF_ALL

sbatch < $JOB.sbatch
