#!/bin/bash

##########
#update the variables below as needed
##########

JOB=TETSHplus_B3LYP_TZP_KlamtWater_solvfrag_neutral.CH2	#this is the name of your job
		#make sure there are no spaces in the name
CURDIR=`'pwd'`  #do not change this line
TIME='24:00:00' #run time (hh:mm:ss) - 2 hours
NODES=1		#total number of nodes
TASKS=128        #total number of mpi tasks requested
		#should be 128 tasks per node

#########
#Do not change this next section!
#########
cat > $JOB.sbatch << EOF_ALL
#!/bin/sh

#SBATCH -J $JOB  	         # job name
#SBATCH -o $CURDIR/$JOB.out
#SBATCH -e $CURDIR/$JOB.err
#SBATCH -N $NODES                # total number of nodes 
#SBATCH -n $TASKS                # total number of mpi tasks requested
#SBATCH -t $TIME                 # run time (hh:mm:ss) - 1.5 hours
#SBATCH --exclude=c004
#!/bin/sh

AMS_JOBNAME=$JOB $AMSBIN/ams << eor

########
#replace the lines below with your adf input file
#starting with the "Task"
########

Task SinglePoint
System
    Atoms
        H 0.7231834598980774 2.020779888804515 -1.290072271269119 region=CH2 adf.R=1.30
        C 0.09718174200404851 1.135494251796135 -1.283491784181505 region=CH2 adf.R=2.00
        H -0.5803164279058256 1.142763906953427 -2.131278024054463 region=CH2 adf.R=1.30
    End
    Symmetrize Yes
    BondOrders
         2 1 1.0
         2 3 1.0
    End
End
Symmetry
    SymmetrizeTolerance 1.0e-7
End

Engine ADF
    Basis
        Type TZP
        Core None
    End
    XC
        Hybrid B3LYP
    End
    Title CH2 fragment
    Relativity
        Level None
    End
    Symmetry NOSYM
    Solvation
        Surf Delley
        Solv name=Water cav0=0.0 cav1=0.0067639
        Charged method=CONJ
        C-Mat POT
        SCF VAR ALL 
        CSMRSP
    End
    NOSYMFIT
EndEngine
eor

########
#do not change the rest of the file!
########

cp $JOB.results/adf.rkf CH2.rkf
mv $JOB.results/ams.log $JOB.logfile
rm slurm-*.out

EOF_ALL

sbatch < $JOB.sbatch
